# This script monitors the log file generated by the robocopy command.

# Define the log file path
$currentDate = Get-Date -Format "MMddyyyy"
$username = (whoami).Split('-')[1]
$logFilePath = "D:\datatransfer_all-$currentDate`_$username`_test.txt"

Write-Host "Monitoring log file: $logFilePath"
Write-Host "Press any key to stop monitoring..."

# Variable to control the monitoring loop
$stopMonitoring = $false

# Monitor the log file in real-time
$monitorJob = Start-Job -ScriptBlock {
    param($logFilePath)
    while (-not (Test-Path -Path "C:\stopMonitoring.txt")) {
        if (Test-Path -Path $logFilePath) {
            Get-Content -Path $logFilePath -Wait -Tail 10
        }
        Start-Sleep -Milliseconds 500
    }
} -ArgumentList $logFilePath

# Check for key press to stop monitoring
while (-not $stopMonitoring) {
    if ($Host.UI.RawUI.KeyAvailable) {
        $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
        $stopMonitoring = $true
        New-Item -Path "C:\stopMonitoring.txt" -ItemType File -Force | Out-Null
    }
    Start-Sleep -Milliseconds 500
}

# Stop the monitoring job
Stop-Job -Job $monitorJob
Remove-Job -Job $monitorJob

# Clean up the control file
Remove-Item -Path "C:\stopMonitoring.txt" -Force

Write-Host "Monitoring stopped."